rvm:
  - jruby-9.2.0.0
  - jruby-head
jdk:
  - openjdk8
branches:
  only:
    - master
    - /-dev|-feature|-fix/
env:
  global:
    JRUBY_OPTS: "-J-Xmx896M"
script: bundle exec rake $TASK
matrix:
  include:
    - rvm: jruby-9.2.0.0
      env: TASK=integration
    - rvm: jruby-9.2.0.0
      env: RAKE_VERSION="~>10.1"
    - rvm: jruby-9.2.0.0
      env: RAKE_VERSION="~>11.2"
    - rvm: jruby-9.2.0.0
      env: RAKE_VERSION="~>12.3"
  allow_failures:
    - rvm: jruby-head
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
before_install:
  - git fetch --unshallow
  - gem update --system 2.6.14
  - gem --version
  - rvm @global do gem uninstall bundler -a -x -I || true
  - gem uninstall bundler -a -x -I || true
  - gem install bundler -v '< 2'
