rvm:
  - jruby-9.0.0.0.pre1
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - 2.x-dev
env:
  - JRUBY_OPTS="--server -Xcompile.invokedynamic=false"
matrix:
  include:
    - rvm: jruby-head
      env: JRUBY_OPTS="--server -Xcompile.invokedynamic=false"
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
before_install:
  - sudo apt-get update && sudo apt-get install git
  - git fetch --unshallow
  - gem install bundler --pre
